global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring_boot_prometheus"
    metrics_path: "/apis/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["springradler:9001"]
